language: python

env:
    global:
        # Set defaults to avoid repeating in most cases
        - NUMPY_VERSION=1.13
        - ANSWER_VER=1

matrix:
    include:

        # Try all python versions with the latest numpy
        - python: 2.7
          env: PYTHON='python'
        - python: 3.5
          env: CMD="py.test soxs/tests --answer_dir=$PWD/soxs_test_data3" PYTHON='python3'
        - python: 3.6
          env: CMD="py.test soxs/tests --answer_dir=$PWD/soxs_test_data3" PYTHON='python3'
        - python: 3.6
          env: CMD='coverage run --source soxs -m py.test'; PYTHON='python3'

before_install:

    - wget http://hea-www.cfa.harvard.edu/~jzuhone/soxs_responses.tar.gz
    - tar -zxvf soxs_responses.tar.gz
    #- wget http://hea-www.cfa.harvard.edu/~jzuhone/soxs_test_data2_${ANSWER_VER}.tar.gz
    #- tar -zxvf soxs_test_data2_${ANSWER_VER}.tar.gz
    - wget http://hea-www.cfa.harvard.edu/~jzuhone/soxs_test_data3_${ANSWER_VER}.tar.gz
    - tar -zxvf soxs_test_data3_${ANSWER_VER}.tar.gz

    - mkdir -p $HOME/.config/soxs
    - printf "[soxs]\nresponse_path = $PWD/soxs_responses" >> $HOME/.config/soxs/soxs.cfg

    # Use utf8 encoding. Should be default, but this is insurance against
    # future changes
    - export PYTHONIOENCODING=UTF8
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda

    # UPDATE APT-GET LISTINGS
    - sudo apt-get update

install:

    # CONDA
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test

    # CORE DEPENDENCIES
    - conda config --add channels conda-forge
    - conda install --yes numpy=$NUMPY_VERSION pytest pip astropy scipy cython h5py tqdm pyyaml
    - conda install --yes -c astropy pyregion
    
    # COVERAGE DEPENDENCIES
    - pip install coverage coveralls
    - $PYTHON setup.py develop

script:

    - $CMD

after_success:
    - if [[ $CMD == 'coverage run --source soxs -m py.test' ]]; then
          coveralls --rcfile='soxs/tests/coveragerc';
      fi
